// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zggvkswkstmdemlvcwzv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpnZ3Zrc3drc3RtZGVtbHZjd3p2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3NjM1ODQsImV4cCI6MjA3MDMzOTU4NH0.LCcI1R1aGD_G-3tOwhPbMNhSKDNc8Sk2HyA8b3sMaL8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});